[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Helicon"
authors = [{name = "Daoyi", email = "lidaoyi16@hotmail.com"}]
dynamic = ["version", "description"]
